# Generated by Django 4.1.7 on 2023-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(default="00000", max_length=255),
            preserve_default=False,
        ),
    ]
