# Generated by Django 4.2 on 2023-04-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20230405_1504"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion", old_name="discout", new_name="discount",
        ),
    ]
